### ISSUE TITLE
Implement "deactivated" mechanism.

### ISSUE THREAD

**Issue by anikitinDSR** [cheqd/did-resolver#5]
There is an issue on `cheqd-noded` for adding `deactivated` mechanism on the ledger side. 
Here is:
https://github.com/cheqd/cheqd-node/issues/315
Need to support this functionality on resolver side too.

# Links for context
https://w3c-ccg.github.io/did-resolution/

The output for DID which was deactivated should be:
https://w3c-ccg.github.io/did-resolution/#resolving-algorithm
`3.3` point.

**Comment by Tweeddalex** [comment]
@anikitinDSR can we close this issue? Can you confirm this is completed for the next release?
